export const recommendedFonts = [
  'Sansita',
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Oswald',
  'Source Sans 3',
  'Aclonica',
  'Aguafina Script',
  'Akronim',
  'Alumni Sans Collegiate One',
  'Amarante',
  'Amita',
  'Angkor',
  'Are You Serious',
  'Asset',
  'Chokokutai',
  'Itim',
  'Noto Sans Elbasan',
  'Rubik Wet Paint',
  'Tiny5',
  'Anton SC',
  'Danfo',
  'Noto Serif Telugu',
  'Anton',
  'Pacifico',
  'Lobster',
  'Lilita One',
  'Shadows Into Light',
  'Satisfy',
  'DM Serif Display',
  'Rowdies',
  'Sixtyfour Convergence',
  'Alfa Slab One'
]